id: 1fdc98bcf52c4c9a9ce2a2916d468d5a
title: Toh_252-The_Fourfold_Accomplishment-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-010
  eft-text-version: 1.0.1 2021
